### PR TITLE
Improve Usage Examples

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
I assume the last 2 commits are inspired by https://github.com/sociomantic-tsunami/dlsproto/issues/8? You may have misinterpreted what I meant in that issue: it wasn't intended to be about the usage examples.

**Comment by nemanja-boric-sociomantic** [comment]
Oh, right. Would you like me to remove the last two commits (not make any notes here), or is the documentation here and at the definition points in order?

**Comment by gavin-norman-sociomantic** [comment]
I feel it's maybe excessive in the usage examples.

**Comment by nemanja-boric-sociomantic** [comment]
Updated with the last two commits dropped.

**Pull request merged**
