### PR TITLE
 Test with newer versions of DMD, including upstream

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
:tada:

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
:+1:

**Comment by nemanja-boric-sociomantic** [comment]
Maybe push ocean to alpha.3 now :angel:  :-)

**Comment by mathias-lang-sociomantic** [comment]
Hum, it needs `unregisterSocket` to be implemented in the `DlsConnectionHandler`.
But judging from the code, it might be better to implement it in swarm directly. In which case swarm have to be updated first.
What do you think ?

**Comment by nemanja-boric-sociomantic** [comment]
Hm, that's strange, because they should implement `IFiberConnectionHandlerBase`, which already implements this.

**Comment by nemanja-boric-sociomantic** [comment]
So, this class should be implemented by `DlsConnectionHandler`: https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/node/connection/ConnectionHandler.d#L381-L382

and that extends this ocean class, which already has this:

https://github.com/sociomantic-tsunami/ocean/blob/v4.x.x/src/ocean/net/server/connection/IFiberConnectionHandler.d#L224

**Comment by nemanja-boric-sociomantic** [comment]
Updating your branch to `v4.0.0-alpha.2` works for me.

**Comment by nemanja-boric-sociomantic** [comment]
Oh, I just realized what I just did. It needs alpha 3.

**Comment by nemanja-boric-sociomantic** [comment]
Ah, damn, it fails on the `FlexibleByteQueue` changes in the ocean v4.0.0. This needs swarm update, that's for sure. cc @david-eckardt-sociomantic @mihails-strasuns-sociomantic

**Comment by mathias-lang-sociomantic** [comment]
In the meantime can we bring this in ? My point is to ensure that we get all tsunami projects to compile with upstream, not ensure compatibility with the newest ocean.

**Comment by nemanja-boric-sociomantic** [comment]
Thanks for the work!

**Pull request merged**
